export const START_WORKOUT_EXECUTION = 'START_WORKOUT_EXECUTION';
export const UPDATE_CURRENT_ACTION_REMAINING_TIME = 'UPDATE_CURRENT_ACTION_REMAINING_TIME';
export const UPDATE_WORKOUT_EXECUTION_STATUS = 'UPDATE_WORKOUT_EXECUTION_STATUS';
export const UPDATE_PLAY_STATE = 'UPDATE_PLAY_STATE';

export type ACTION_TYPES =
  | 'START_WORKOUT_EXECUTION'
  | 'UPDATE_CURRENT_ACTION_REMAINING_TIME'
  | 'UPDATE_WORKOUT_EXECUTION_STATUS'
  | 'UPDATE_PLAY_STATE';
