export const START_WORKOUT_EXECUTION = 'START_WORKOUT_EXECUTION';
export const UPDATE_CURRENT_ACTION_REMAINING_TIME = 'UPDATE_CURRENT_ACTION_REMAINING_TIME';

export type ACTION_TYPES = 'START_WORKOUT_EXECUTION' | 'UPDATE_CURRENT_ACTION_REMAINING_TIME';