export const ADD_SET = 'ADD_SET';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';
export const UPDATE_CURRENT_SET = 'UPDATE_CURRENT_SET';
export const REMOVE_CURRENT_SET = 'REMOVE_CURRENTZ_SET';
export const UPDATE_SET_REST_TIME = 'UPDATE_SET_REST_TIME';
export const UPDATE_EXERCISE_REST_TIME = 'UPDATE_EXERCISE_REST_TIME';
export const UPDATE_EXERCISE_TRAIN_TIME = 'UPDATE_EXERCISE_TRAIN_TIME';
export const UPDATE_CURRENT_SET_LOOP_QUANTITY = 'UPDATE_CURRENT_SET_LOOP_QUANTITY';

export type ACTION_TYPES =
  | 'ADD_EXERCISE'
  | 'REMOVE_EXERCISE'
  | 'UPDATE_EXERCISE_TRAIN_TIME'
  | 'REMOVE_CURRENT_SET'
  | 'UPDATE_SET_REST_TIME'
  | 'UPDATE_CURRENT_SET'
  | 'REMOVE_SET'
  | 'UPDATE_EXERCISE_REST_TIME'
  | 'UPDATE_CURRENT_SET_LOOP_QUANTITY'
  | 'ADD_SET';
