export const ADD_EXERCISE = 'ADD_EXERCISE';
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';
export const UPDATE_EXERCISE_TRAIN_TIME = 'UPDATE_EXERCISE_TRAIN_TIME';
export const UPDATE_EXERCISE_REST_TIME = 'UPDATE_EXERCISE_REST_TIME';
export const UPDATE_CURRENT_SET_LOOP_QUANTITY = 'UPDATE_CURRENT_SET_LOOP_QUANTITY';

export type ACTION_TYPES = 'ADD_EXERCISE'|'REMOVE_EXERCISE'|'UPDATE_EXERCISE_TRAIN_TIME'|'UPDATE_EXERCISE_REST_TIME' | 'UPDATE_CURRENT_SET_LOOP_QUANTITY';