# This is a basic workflow to help you get started with Actions
name: CI-CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          yarn
      # build and test the apps
      - name: Test the app
        run: |
          yarn test
      - name: Build the app
        run: |
          yarn build
      - name: Vercel Deployment
  # You may pin to the exact commit or the version.
  # uses: xmflsct/action-vercel-deployment@dfd18ea029d56a90ce06c154cb40de413840f151
        uses: xmflsct/action-vercel-deployment@v0.5.3
        with:
          # Your token at Vercel. See https://vercel.com/account/tokens
          vercelToken: ${{ secrets.VERCEL_TOKEN }}
          # Your Organization ID at Vercel.
          vercelOrgId: ${{ secrets.VERCEL_ORGANIZATION_ID }}
          # Your Project ID at Vercel.
          vercelProjectId: ${{ secrets.VERCEL_PROJECT_ID }}
          # Your token at GitHub. See https://github.com/settings/tokens
          githubToken: ${{ secrets.ACCOUNT_GITHUB_TOKEN }}
          # If you would like to build through GitHub Actions inatead of Vercel.
         
          assignDomain: https://hiit-maker.io/workout
